### ISSUE TITLE
Doesn't work when the option show correct answer is off

### ISSUE THREAD

**Issue by Dhifan** [gbaranski/quizizz-cheat#1]
please fix this
![image](https://user-images.githubusercontent.com/76167583/102497053-c2b21200-40aa-11eb-9944-01294dce058b.png)

**Comment by gbaranski** [comment]
@Dhifan can you send me link to this quiz?

**Comment by Dhifan** [comment]
@gbaranski https://quizizz.com/admin/quiz/start_new/5fdb816c91c3b4001f97e80f
well, i'am create this dummy quiz for testing a script and i setting it the correct answer is not shown 
![image](https://user-images.githubusercontent.com/76167583/102512643-d8c8ce00-40bc-11eb-82ea-ae53a39db8cd.png)

**Comment by gbaranski** [comment]
Okay I see the problem. I'll try to search for some different way to retrieve answers.

**Comment by Dhifan** [comment]
@gbaranski thank you very much, i greatly appreciate what you did.

**Comment by ghost** [comment]
Hello @gbaranski, I appreciate your work very much. I would like to ask if you have found an alternative way to retrieve the answers? Most teachers often take off the 'show correct answers' option which is pretty frustrating. 
I am talking about the Live Quizzes. Hope you're having a good day!

**Comment by gbaranski** [comment]
> Hello @gbaranski, I appreciate your work very much. I would like to ask if you have found an alternative way to retrieve the answers? Most teachers often take off the 'show correct answers' option which is pretty frustrating.
> I am talking about the Live Quizzes. Hope you're having a good day!

I didn't found, but I know that some guy did it, but he obfuscated everything, and the code is probably also working on server-side, here is the [link](https://github.com/Im-Beast/Im-Beast.github.io/blob/42805b7335fcadb93f317e0eb894178377e82c30/scripts/script.obf.js). I don't have currently time to search for some new way to retrieve answers, feel free to contribute.

Have a nice day!

**Comment by gbaranski** [comment]
~~@danielvdh42 @Dhifan the issue was solved by changing the way to retrieve answers, now it also works in test mode and even when teacher does not set option to give answers.~~ 
EDIT: see #8  #9
