### ISSUE TITLE
Jak to działa?

### ISSUE THREAD

**Issue by 1ncvv** [gbaranski/quizizz-cheat#10]
Czy gdy podam nick innego gracza, ten będzie miał wszystkie złe odpowiedzi i żadna nie będzie poprawna?

**Comment by fhodun** [comment]
Tak będzie.

**Comment by gbaranski** [comment]
He won't fail every answer, only those on which you execute the script, so for example if you use this script on question 3 using nick of player X, player X won't receive points on question 3 even if he gave valid answer. But he might receive points for other answers on which you did not executed the script.
