### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Javi3rV** [gbaranski/quizizz-cheat#13]
The script is now automatic in all questions from a quiz.
Last method was more undetectable on the naked eye, if the teacher is watching your screen, u could wait so he wouldn't notice anyhing. Now is more evident you are cheating bc answers are always displayed...
It would be nice if this same script worked only for the actual question, so u can execute when u want! that would be OP.
Sry for my bad english xD

**Comment by gbaranski** [comment]
> The script is now automatic in all questions from a quiz.
> Last method was more undetectable on the naked eye, if the teacher is watching your screen, u could wait so he wouldn't notice anyhing. Now is more evident you are cheating bc answers are always displayed...
> It would be nice if this same script worked only for the actual question, so u can execute when u want! that would be OP.
> Sry for my bad english xD

Check [readme](https://github.com/gbaranski/quizizz-cheat/blob/master/README.md), there is information on how to use the old  method
