### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Javi3rV** [gbaranski/quizizz-cheat#15]
It would be nice if this script worked only in the active question, so it would be undetectable even for the teachers.

**Comment by gbaranski** [comment]
> It would be nice if this script worked only in the active question, so it would be undetectable even for the teachers.

I don't want to mantain two seperate version specially for you.

**Comment by Javi3rV** [comment]
Oh sorry for replying you that many times I didnt notice you were talking
to me here.
It was just a suggestion.
