### ISSUE TITLE
Doesn't work in private quizzes,

### ISSUE THREAD

**Issue by ghost** [gbaranski/quizizz-cheat#16]

**Comment by gbaranski** [comment]
What do you mean by "doesn't work"? Can you provide any information what's happening?

**Comment by P-tngf** [comment]
i wil describe that problem . when you enjoin a quizziz game which is created by somebody at that moment that code is not working
![Screenshot (22)](https://user-images.githubusercontent.com/62495635/108595326-e6971a00-73b1-11eb-912a-a60dd5b0856a.png)
