### ISSUE TITLE
Nowa metoda nie działą w trybie Live / New method doesn't work on Live mode

### ISSUE THREAD

**Issue by 1ncvv** [gbaranski/quizizz-cheat#23]
Wkleiłem skrypt z nowej metody do konsoli, ale otrzymałem błąd. Używałem M$ Edge. / I put the new mothod in console, but i recived error. I used M$ Edge.

**Comment by gbaranski** [comment]
Use [alternative method](https://github.com/gbaranski/quizizz-cheat#sending-answers-as-someone-else)
