### ISSUE TITLE
Pronouns

### ISSUE THREAD

**Issue by Shday7heyrat** [gbaranski/quizizz-cheat#27]
So i was using the thing and it showed the He pronoun i reccomend changing the pronoun to They to adress Men/Woman/Non-Binary and others, Thank you in advance!

**Comment by NeededTundra711** [comment]
yo, shut the fuck up. you deadass sound retarded as shit over here saying "wE sHouLd UsE ThEse pRonOunS".

**Comment by MrCrypticxDev** [comment]
LMFAO, this is sooo funny.

**Comment by peebowo** [comment]
bro beefin on github

**Comment by gbaranski** [comment]
closed by #51
