### ISSUE TITLE
Test Mode does not work

### ISSUE THREAD

**Issue by Nediar23** [gbaranski/quizizz-cheat#4]
The Script don´t work in Test mode, you know an alternative script.

**Comment by gbaranski** [comment]
@Nediar23 What do you mean by test mode?

**Comment by Nediar23** [comment]
When you´re a teacher and make an exam, the script don´t work for the participants. The spanish name is (Examen).

**Comment by Nediar23** [comment]
It appears:

Unable to detect https://cf.quizizz.com/assets/v3/j/scripts/js/vendor_misc.5dd1acd0db99d69238db.js
automaticcly answer type structure.

![LOL](https://user-images.githubusercontent.com/78044260/105901907-ed698180-5feb-11eb-9df1-db357d09d27a.png)

**Comment by gbaranski** [comment]
Works only on live quize. Follow the instructions.
If problem still occurs, expand the message above "Unable to detect automaticcly answer type"

**Comment by Nediar23** [comment]
I expand the message:

![2](https://user-images.githubusercontent.com/78044260/105903597-11c65d80-5fee-11eb-9a2f-c3192646e275.png)
![1](https://user-images.githubusercontent.com/78044260/105903603-125ef400-5fee-11eb-9be2-e9a2719e613d.png)
![3](https://user-images.githubusercontent.com/78044260/105903605-12f78a80-5fee-11eb-87e3-1f77a9ff5357.png)

**Comment by gbaranski** [comment]
Expand everything except `__proto__`

**Comment by Nediar23** [comment]
Response: 
{__cid__: null, response: {…}, playerId: "Messi", question: {…}, player: {…}, …}
err: null
leaderboard: Array(2)
0:
monsterId: 35
origin: "web"
playerId: "Messi"
rank: 1
score: 0
userAddons: null
__proto__: Object
1:
monsterId: 19
origin: "web"
playerId: "Axl Andrés Masso"
rank: 2
score: 0
userAddons: null
__proto__: Object
length: 2
__proto__: Array(0)
player:
__proto__: Object
playerCount: 2
playerId: "Messi"
powerupEffects: Array(0)
length: 0
__proto__: Array(0)
question:
structure: {}
__proto__: Object
response:
attempt: 0
createdAt: "2021-01-26T20:57:55.396Z"
deleted: false
elapsed: 0
id: "601082535ac8bb001beaabee"
playerId: "Messi"
questionId: "60106084f0328b001c8d7646"
questionType: "MSQ"
response: Array(0)
length: 0
__proto__: Array(0)
teamAdjustment: 0
timeTaken: 8902
_v: "r2"
__proto__: Object
__cid__: null
__proto__: Object


**Unable to detect automaticcly answer type**
{structure: {…}}
structure:
__proto__: Object
__proto__:
constructor: ƒ Object()
arguments: (...)
assign: ƒ assign()
arguments: (...)
caller: (...)
length: 2
name: "assign"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
No hay ninguna propiedad
caller: (...)
create: ƒ create()
arguments: (...)
caller: (...)
length: 2
name: "create"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
No hay ninguna propiedad
defineProperties: ƒ defineProperties()
arguments: (...)
caller: (...)
length: 2
name: "defineProperties"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
No hay ninguna propiedad
defineProperty: ƒ defineProperty()
arguments: (...)
caller: (...)
length: 3
name: "defineProperty"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
No hay ninguna propiedad
entries: ƒ entries()
arguments: (...)
caller: (...)
length: 1
name: "entries"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
No hay ninguna propiedad
freeze: ƒ freeze()
arguments: (...)
caller: (...)
length: 1
name: "freeze"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
fromEntries: ƒ fromEntries()
arguments: (...)
caller: (...)
length: 1
name: "fromEntries"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
No hay ninguna propiedad
getOwnPropertyDescriptor: ƒ getOwnPropertyDescriptor()
arguments: (...)
caller: (...)
length: 2
name: "getOwnPropertyDescriptor"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
No hay ninguna propiedad
getOwnPropertyDescriptors: ƒ getOwnPropertyDescriptors()
arguments: (...)
caller: (...)
length: 1
name: "getOwnPropertyDescriptors"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
getOwnPropertyNames: ƒ getOwnPropertyNames()
arguments: (...)
caller: (...)
length: 1
name: "getOwnPropertyNames"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
No hay ninguna propiedad
getOwnPropertySymbols: ƒ getOwnPropertySymbols()
arguments: (...)
caller: (...)
length: 1
name: "getOwnPropertySymbols"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
No hay ninguna propiedad
getPrototypeOf: ƒ getPrototypeOf()
arguments: (...)
caller: (...)
length: 1
name: "getPrototypeOf"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
No hay ninguna propiedad
is: ƒ is()
arguments: (...)
caller: (...)
length: 2
name: "is"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
isExtensible: ƒ isExtensible()
arguments: (...)
caller: (...)
length: 1
name: "isExtensible"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
isFrozen: ƒ isFrozen()
arguments: (...)
caller: (...)
length: 1
name: "isFrozen"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
isSealed: ƒ isSealed()
arguments: (...)
caller: (...)
length: 1
name: "isSealed"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
keys: ƒ keys()
length: 1
name: "Object"
preventExtensions: ƒ preventExtensions()
arguments: (...)
caller: (...)
length: 1
name: "preventExtensions"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
prototype:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
seal: ƒ seal()
arguments: (...)
caller: (...)
length: 1
name: "seal"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
setPrototypeOf: ƒ setPrototypeOf()
arguments: (...)
caller: (...)
length: 2
name: "setPrototypeOf"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
values: ƒ values()
arguments: (...)
caller: (...)
length: 1
name: "values"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
hasOwnProperty: ƒ hasOwnProperty()
arguments: (...)
caller: (...)
length: 1
name: "hasOwnProperty"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
isPrototypeOf: ƒ isPrototypeOf()
arguments: (...)
caller: (...)
length: 1
name: "isPrototypeOf"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
propertyIsEnumerable: ƒ propertyIsEnumerable()
arguments: (...)
caller: (...)
length: 1
name: "propertyIsEnumerable"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
toLocaleString: ƒ toLocaleString()
arguments: (...)
caller: (...)
length: 0
name: "toLocaleString"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
toString: ƒ toString()
arguments: (...)
caller: (...)
length: 0
name: "toString"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
valueOf: ƒ valueOf()
arguments: (...)
caller: (...)
length: 0
name: "valueOf"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
__defineGetter__: ƒ __defineGetter__()
arguments: (...)
caller: (...)
length: 2
name: "__defineGetter__"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
__defineSetter__: ƒ __defineSetter__()
arguments: (...)
caller: (...)
length: 2
name: "__defineSetter__"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
__lookupGetter__: ƒ __lookupGetter__()
arguments: (...)
caller: (...)
length: 1
name: "__lookupGetter__"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
__lookupSetter__: ƒ __lookupSetter__()
arguments: (...)
caller: (...)
length: 1
name: "__lookupSetter__"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
get __proto__: ƒ __proto__()
arguments: (...)
caller: (...)
length: 0
name: "get __proto__"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
set __proto__: ƒ __proto__()
arguments: (...)
caller: (...)
length: 1
name: "set __proto__"
__proto__: ƒ ()
[[Scopes]]: Scopes[0]
No hay ninguna propiedad

**Comment by Ninidze1** [comment]
I entered quiz from 2 accaunt and when I entered name of other i got correct answers. However other one whose name was used is getting incorrect answers, eventhoug they are true. is it right to use it in real quizz :D ?

**Comment by gbaranski** [comment]
@Nediar23 I've updated method of retreiving answers, now test mode also works.

**Comment by gbaranski** [comment]
Should work now
