### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Arvbdtiy6** [gbaranski/quizizz-cheat#50]
I WANT OTHER CODE BUT FOR GOOGLE FORMS THAT SHOWS THE AWNSERS OR AN EXTENTION THAT SHOWS IN OTHER PLACE AUTOM THE CORRECT AWNSERS.
IN TXT, CODE, LIST OR NOTE
PLS PLS :,)

**Comment by Arvbdtiy6** [comment]
Quiero para GOOGLE FORMS
UN MÉTODO IGUAL PERO UNIVERSAL

**Comment by gbaranski** [comment]
no, that’s not possible because of google forms design.

**Comment by Arvbdtiy6** [comment]
But Someone, annonymous, other hack group do it
