### ISSUE TITLE
Why's it obfusticated, what are you tryna hide?

### ISSUE THREAD

**Issue by Raz-js** [gbaranski/quizizz-cheat#59]

**Comment by gbaranski** [comment]
nothing, the bundle is obfuscated, but it's literally compilation output of the source code that is in the `src/` folder, if you don't believe, feel free to compile it yourselves. 

I obfuscated it so people that can't build JS project cannot change the code, specifically this line:

https://github.com/gbaranski/quizizz-cheat/blob/master/src/index.ts#L84-L87

Few people tried to take the code, change the author and republish it claiming that they made it, and they could easily do that when the code wasn't obfuscated.
