### ISSUE TITLE
Unsafe-Eval

### ISSUE THREAD

**Issue by jacktang22** [gbaranski/quizizz-cheat#60]
it saids that eval() is unsafe
How to get rid of it?

**Comment by gbaranski** [comment]
you could download the code, from dist/ folder and then just paste it into the console, but that’s inconvenient and will do the same as the eval.

eval() could be unsafe if the github hosting or my account is hijacked and the dist/ code replaced.

but even if, that’s just the quizizz page, the code executed via the eval cannot access other websites and thus cannot access anything crucial, unless your quizizz account is that important to you.
